### ISSUE TITLE
lovelace-header-cards broken on Core 2023.4.0.

### ISSUE THREAD

**Issue by WarC0zes** [gadgetchnnel/lovelace-header-cards#10]
Hi,
lovelace-header-cards no longer works since the release of core 2023.4.0.
There is no error in the logs, the only one I found is in google chrome.

![header card broken](https://user-images.githubusercontent.com/91471397/230313368-27adb5ce-a158-4b43-b92e-f821bdc16770.png)

@gadgetchnnel Can you fix this problem, I love your card and would be disappointed to have to remove it.

**Comment by Loic691** [comment]
Hi all
Same issue for me since HA update to 2023.4.0

**Comment by gadgetchnnel** [comment]
Can you please try with the latest version, 0.0.10, which has a fix which should resolve this.

**Comment by WarC0zes** [comment]
> Can you please try with the latest version, 0.0.10, which has a fix which should resolve this.

It's good with the  latest version 0.0.10. You were fast, thank you very much

**Comment by Loic691** [comment]
Yes it's ok with this version.
thanks
