### ISSUE TITLE
Header card not visible in dashboard with single view

### ISSUE THREAD

**Issue by robbse81** [gadgetchnnel/lovelace-header-cards#2]
Hi, thanks for this great work which will help a lot of us to create awesome dashboards!

I followed the installation instructions and the cards are working as described.

However, if I start a new dashboard with only a single view, the cards are not shown. When I add a 2nd view, the cards show up.
Is this a bug, or is this behaviour intended?

**Comment by gadgetchnnel** [comment]
I've changed how it positions the cards in the latest version, 0.0.5, which should fix this.
Can you please try it and see if it works for you?

**Comment by robbse81** [comment]
That was fast. Yes it works now, thank you very much.
