### ISSUE TITLE
Badges not updating

### ISSUE THREAD

**Issue by wshankles** [gadgetchnnel/lovelace-header-cards#5]
Badges do not update quickly. I have a sensor displaying current watts consumed so it changes frequently. The badges don't update and comparing the current reading vs what the badges say it's usually way off. Also I uninstalled header cards and regular badges won't come back.

**Comment by gadgetchnnel** [comment]
There were updates in the least version, 0.0.10, which should improve the updating of badges and cards.
Please update to this version, and raise a new issue if there are still problems.
