### ISSUE TITLE
Integration broken in Home Assistant 2023.4.0

### ISSUE THREAD

**Issue by Haronych** [gadgetchnnel/lovelace-header-cards#9]
Integration no longer works after Home Assistant 2023.4.0 update (

**Comment by WarC0zes** [comment]
lol, at same time https://github.com/gadgetchnnel/lovelace-header-cards/issues/10

**Comment by Haronych** [comment]
Thanks! Version 0.0.10 solves the problem

**Comment by kwkid** [comment]
Life is good...this fixes it for me....thx for the quick response

**Comment by boheme61** [comment]
I got the items back, but no items react on "justify_content: start"
Does anyone have problems with "justify_content" ?

**Comment by gadgetchnnel** [comment]
@boheme61 Can you raise a new issue with the details, and I'll close this one as discussing two different issues here will cause confusion. In particular, let me know what you mean by "no items react" when you use `justify_content: start`? That they don't react when you click on them or the position isn't changing as you expect?
